# Setup
title: Gymnasium Courses Prototype
# url: https://staging.thegymcms.com
# gymurl: https://courses.gymna.si
timezone: America/New_York


# Building

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'netlify.toml'
  - '.jekyll-cache'

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
